
package wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BEPTGlobal", targetNamespace = "http://globalservice.ws.bept.ids.by/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BEPTGlobal {


    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetPartyByGLNResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPartyByGLN", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetPartyByGLN")
    @ResponseWrapper(localName = "getPartyByGLNResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetPartyByGLNResponse")
    public GetPartyByGLNResp getPartyByGLN(
        @WebParam(name = "request", targetNamespace = "")
        GetPartyByGLNReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.CleanTradeitemsOfPoolByDeleteTimeResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cleanTradeitemsOfPoolByDeleteTime", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.CleanTradeitemsOfPoolByDeleteTime")
    @ResponseWrapper(localName = "cleanTradeitemsOfPoolByDeleteTimeResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.CleanTradeitemsOfPoolByDeleteTimeResponse")
    public CleanTradeitemsOfPoolByDeleteTimeResp cleanTradeitemsOfPoolByDeleteTime(
        @WebParam(name = "request", targetNamespace = "")
        CleanTradeitemsOfPoolByDeleteTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetCheckGTIN29Resp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckGTIN29", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetCheckGTIN29")
    @ResponseWrapper(localName = "getCheckGTIN29Response", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetCheckGTIN29Response")
    public GetCheckGTIN29Resp getCheckGTIN29(
        @WebParam(name = "request", targetNamespace = "")
        GetCheckGTIN29Req request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetClassificatorResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClassificator", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetClassificator")
    @ResponseWrapper(localName = "getClassificatorResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetClassificatorResponse")
    public GetClassificatorResp getClassificator(
        @WebParam(name = "request", targetNamespace = "")
        GetClassificatorReq request);

    /**
     * 
     * @param request
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentTime", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetCurrentTime")
    @ResponseWrapper(localName = "getCurrentTimeResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetCurrentTimeResponse")
    public XMLGregorianCalendar getCurrentTime(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetFullPartyByGLNResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFullPartyByGLN", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetFullPartyByGLN")
    @ResponseWrapper(localName = "getFullPartyByGLNResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetFullPartyByGLNResponse")
    public GetFullPartyByGLNResp getFullPartyByGLN(
        @WebParam(name = "request", targetNamespace = "")
        GetFullPartyByGLNReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetFunctionalnameByGTINResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFunctionalnameByGTIN", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetFunctionalnameByGTIN")
    @ResponseWrapper(localName = "getFunctionalnameByGTINResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetFunctionalnameByGTINResponse")
    public GetFunctionalnameByGTINResp getFunctionalnameByGTIN(
        @WebParam(name = "request", targetNamespace = "")
        GetFunctionalnameByGTINReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetFunctionalnameByGTINResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFunctionalnameByGTIN2", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetFunctionalnameByGTIN2")
    @ResponseWrapper(localName = "getFunctionalnameByGTIN2Response", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetFunctionalnameByGTIN2Response")
    public GetFunctionalnameByGTINResp getFunctionalnameByGTIN2(
        @WebParam(name = "request", targetNamespace = "")
        GetFunctionalnameByGTINReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.ApiHeaderResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOldHeaderResp", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetOldHeaderResp")
    @ResponseWrapper(localName = "getOldHeaderRespResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetOldHeaderRespResponse")
    public ApiHeaderResponse getOldHeaderResp(
        @WebParam(name = "request", targetNamespace = "")
        ApiHeaderResponse request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.Party
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOldParty", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetOldParty")
    @ResponseWrapper(localName = "getOldPartyResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetOldPartyResponse")
    public Party getOldParty(
        @WebParam(name = "request", targetNamespace = "")
        GetFullPartyByGLNReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.Tradeitem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOldTradeitem", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetOldTradeitem")
    @ResponseWrapper(localName = "getOldTradeitemResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetOldTradeitemResponse")
    public Tradeitem getOldTradeitem(
        @WebParam(name = "request", targetNamespace = "")
        GetTradeitemByGTINReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetPartyByUNPResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPartyByUNP", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetPartyByUNP")
    @ResponseWrapper(localName = "getPartyByUNPResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetPartyByUNPResponse")
    public GetPartyByUNPResp getPartyByUNP(
        @WebParam(name = "request", targetNamespace = "")
        GetPartyByUNPReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetQuotaImportInfoResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuotaImportInfo", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetQuotaImportInfo")
    @ResponseWrapper(localName = "getQuotaImportInfoResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetQuotaImportInfoResponse")
    public GetQuotaImportInfoResp getQuotaImportInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetQuotaImportInfoReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetSimpleTradeitemsByGTINResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSimpleTradeitemsByGTIN", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetSimpleTradeitemsByGTIN")
    @ResponseWrapper(localName = "getSimpleTradeitemsByGTINResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetSimpleTradeitemsByGTINResponse")
    public GetSimpleTradeitemsByGTINResp getSimpleTradeitemsByGTIN(
        @WebParam(name = "request", targetNamespace = "")
        GetSimpleTradeitemsByGTINReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetTIImageKindsByGTINsResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTIImageKindsByGTINs", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTIImageKindsByGTINs")
    @ResponseWrapper(localName = "getTIImageKindsByGTINsResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTIImageKindsByGTINsResponse")
    public GetTIImageKindsByGTINsResp getTIImageKindsByGTINs(
        @WebParam(name = "request", targetNamespace = "")
        GetTIImageKindsByGTINsReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetTradeitemByGTINResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTradeitemByGTIN", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemByGTIN")
    @ResponseWrapper(localName = "getTradeitemByGTINResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemByGTINResponse")
    public GetTradeitemByGTINResp getTradeitemByGTIN(
        @WebParam(name = "request", targetNamespace = "")
        GetTradeitemByGTINReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetTradeitemsByGTINsShortResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTradeitemsByGTINsShort", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemsByGTINsShort")
    @ResponseWrapper(localName = "getTradeitemsByGTINsShortResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemsByGTINsShortResponse")
    public GetTradeitemsByGTINsShortResp getTradeitemsByGTINsShort(
        @WebParam(name = "request", targetNamespace = "")
        GetTradeitemsByGTINsShortReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetTradeitemsOfPoolByModifiedTimeResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTradeitemsOfPoolByModifiedTime", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemsOfPoolByModifiedTime")
    @ResponseWrapper(localName = "getTradeitemsOfPoolByModifiedTimeResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemsOfPoolByModifiedTimeResponse")
    public GetTradeitemsOfPoolByModifiedTimeResp getTradeitemsOfPoolByModifiedTime(
        @WebParam(name = "request", targetNamespace = "")
        GetTradeitemsOfPoolByModifiedTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetVariantByGTINResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVariantByGTIN", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetVariantByGTIN")
    @ResponseWrapper(localName = "getVariantByGTINResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetVariantByGTINResponse")
    public GetVariantByGTINResp getVariantByGTIN(
        @WebParam(name = "request", targetNamespace = "")
        GetVariantByGTINReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchSimpleImportTradeitemsByModifiedTimeResp
     */
    @WebMethod(operationName = "SearchGTINfromDatamarkSystemByModifiedTime")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchGTINfromDatamarkSystemByModifiedTime", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchGTINfromDatamarkSystemByModifiedTime")
    @ResponseWrapper(localName = "SearchGTINfromDatamarkSystemByModifiedTimeResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchGTINfromDatamarkSystemByModifiedTimeResponse")
    public SearchSimpleImportTradeitemsByModifiedTimeResp searchGTINfromDatamarkSystemByModifiedTime(
        @WebParam(name = "request", targetNamespace = "")
        SearchSimpleImportTradeitemsByModifiedTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchPartiesByModifiedTimeResp
     */
    @WebMethod(operationName = "SearchPartiesByModifiedTime")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchPartiesByModifiedTime", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchPartiesByModifiedTime")
    @ResponseWrapper(localName = "SearchPartiesByModifiedTimeResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchPartiesByModifiedTimeResponse")
    public SearchPartiesByModifiedTimeResp searchPartiesByModifiedTime(
        @WebParam(name = "request", targetNamespace = "")
        SearchPartiesByModifiedTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTimeResp
     */
    @WebMethod(operationName = "SearchSimpleTradeitemsByModifiedTime")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchSimpleTradeitemsByModifiedTime", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTime")
    @ResponseWrapper(localName = "SearchSimpleTradeitemsByModifiedTimeResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTimeResponse")
    public SearchSimpleTradeitemsByModifiedTimeResp searchSimpleTradeitemsByModifiedTime(
        @WebParam(name = "request", targetNamespace = "")
        SearchSimpleTradeitemsByModifiedTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTimeResp
     */
    @WebMethod(operationName = "SearchSimpleTradeitemsByModifiedTime2")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchSimpleTradeitemsByModifiedTime2", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTime2")
    @ResponseWrapper(localName = "SearchSimpleTradeitemsByModifiedTime2Response", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTime2Response")
    public SearchSimpleTradeitemsByModifiedTimeResp searchSimpleTradeitemsByModifiedTime2(
        @WebParam(name = "request", targetNamespace = "")
        SearchSimpleTradeitemsByModifiedTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTimeResp
     */
    @WebMethod(operationName = "SearchSimpleTradeitemsByModifiedTime3")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchSimpleTradeitemsByModifiedTime3", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTime3")
    @ResponseWrapper(localName = "SearchSimpleTradeitemsByModifiedTime3Response", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchSimpleTradeitemsByModifiedTime3Response")
    public SearchSimpleTradeitemsByModifiedTimeResp searchSimpleTradeitemsByModifiedTime3(
        @WebParam(name = "request", targetNamespace = "")
        SearchSimpleTradeitemsByModifiedTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchTradeitemsByGLNResp
     */
    @WebMethod(operationName = "SearchTradeitemsByGLN")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchTradeitemsByGLN", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByGLN")
    @ResponseWrapper(localName = "SearchTradeitemsByGLNResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByGLNResponse")
    public SearchTradeitemsByGLNResp searchTradeitemsByGLN(
        @WebParam(name = "request", targetNamespace = "")
        SearchTradeitemsByGLNReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchTradeitemsByGLNAndModifiedTimeResp
     */
    @WebMethod(operationName = "SearchTradeitemsByGLNAndModifiedTime")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchTradeitemsByGLNAndModifiedTime", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByGLNAndModifiedTime")
    @ResponseWrapper(localName = "SearchTradeitemsByGLNAndModifiedTimeResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByGLNAndModifiedTimeResponse")
    public SearchTradeitemsByGLNAndModifiedTimeResp searchTradeitemsByGLNAndModifiedTime(
        @WebParam(name = "request", targetNamespace = "")
        SearchTradeitemsByGLNAndModifiedTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchTradeitemsByModifiedTimeResp
     */
    @WebMethod(operationName = "SearchTradeitemsByModifiedTime")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchTradeitemsByModifiedTime", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByModifiedTime")
    @ResponseWrapper(localName = "SearchTradeitemsByModifiedTimeResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByModifiedTimeResponse")
    public SearchTradeitemsByModifiedTimeResp searchTradeitemsByModifiedTime(
        @WebParam(name = "request", targetNamespace = "")
        SearchTradeitemsByModifiedTimeReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchTradeitemsByNameResp
     */
    @WebMethod(operationName = "SearchTradeitemsByName")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchTradeitemsByName", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByName")
    @ResponseWrapper(localName = "SearchTradeitemsByNameResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByNameResponse")
    public SearchTradeitemsByNameResp searchTradeitemsByName(
        @WebParam(name = "request", targetNamespace = "")
        SearchTradeitemsByNameReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchTradeitemsByOKRB007Resp
     */
    @WebMethod(operationName = "SearchTradeitemsByOKRB007")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchTradeitemsByOKRB007", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByOKRB007")
    @ResponseWrapper(localName = "SearchTradeitemsByOKRB007Response", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByOKRB007Response")
    public SearchTradeitemsByOKRB007Resp searchTradeitemsByOKRB007(
        @WebParam(name = "request", targetNamespace = "")
        SearchTradeitemsByOKRB007Req request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchTradeitemsByTNVEDResp
     */
    @WebMethod(operationName = "SearchTradeitemsByTNVED")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchTradeitemsByTNVED", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByTNVED")
    @ResponseWrapper(localName = "SearchTradeitemsByTNVEDResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchTradeitemsByTNVEDResponse")
    public SearchTradeitemsByTNVEDResp searchTradeitemsByTNVED(
        @WebParam(name = "request", targetNamespace = "")
        SearchTradeitemsByTNVEDReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetTradeitemsByGTINsResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTradeitemsByGTINs", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemsByGTINs")
    @ResponseWrapper(localName = "getTradeitemsByGTINsResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemsByGTINsResponse")
    public GetTradeitemsByGTINsResp getTradeitemsByGTINs(
        @WebParam(name = "request", targetNamespace = "")
        GetTradeitemsByGTINsReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.LogoutResp
     */
    @WebMethod(operationName = "Logout")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.LogoutResponse")
    public LogoutResp logout(
        @WebParam(name = "request", targetNamespace = "")
        LogoutReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.LoginResp
     */
    @WebMethod(operationName = "Login")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Login", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.LoginResponse")
    public LoginResp login(
        @WebParam(name = "request", targetNamespace = "")
        LoginReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetShortTradeitemByGTINResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTradeitemByGTINshort", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemByGTINshort")
    @ResponseWrapper(localName = "getTradeitemByGTINshortResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetTradeitemByGTINshortResponse")
    public GetShortTradeitemByGTINResp getTradeitemByGTINshort(
        @WebParam(name = "request", targetNamespace = "")
        GetShortTradeitemByGTINReq request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.ApiHeaderRequest
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOldHeaderReq", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetOldHeaderReq")
    @ResponseWrapper(localName = "getOldHeaderReqResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.GetOldHeaderReqResponse")
    public ApiHeaderRequest getOldHeaderReq(
        @WebParam(name = "request", targetNamespace = "")
        ApiHeaderRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.consumingwebservice.wsdl.SearchGTINfromDatamarkSystemByGTINResp
     */
    @WebMethod(operationName = "SearchGTINfromDatamarkSystemByGTIN")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchGTINfromDatamarkSystemByGTIN", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchGTINfromDatamarkSystemByGTIN")
    @ResponseWrapper(localName = "SearchGTINfromDatamarkSystemByGTINResponse", targetNamespace = "http://globalservice.ws.bept.ids.by/", className = "com.example.consumingwebservice.wsdl.SearchGTINfromDatamarkSystemByGTINResponse")
    public SearchGTINfromDatamarkSystemByGTINResp searchGTINfromDatamarkSystemByGTIN(
        @WebParam(name = "request", targetNamespace = "")
        SearchGTINfromDatamarkSystemByGTINReq request);

}
